version: "3.9"

services:

  web:
    build: .
    ports:
      - "80:8080"

  mysql:
    image: "mysql:5.7"
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=true
      - MYSQL_DATABASE=summer
      - MYSQL_USER=spring
      - MYSQL_PASSWORD=helehele
